### ISSUE TITLE
SCSS & BEM leren 🎨

### ISSUE THREAD

**Issue by Annevd** [Annevd/Meesterproef#31]
Onder deze issue ga ik aantekeningen maken van de fundamentele principes van SCSS(Sass), de CSS pre-processor & BEM, een veelgebruikte conventie in combinatie met SCSS.

**Wat is het verschil tussen SCSS en Sass?**

Beide kunnen compiled worden naar CSS. Het verschil zit hem in de syntax. SCSS gebruikt vooral dezelfde syntax als CSS, en Sass neemt de `{}` en `;` weg. In beide kan je de extra features die Sass aanbiedt gebruiken.

**Hier zie je een voorbeeld van het verschil in syntax:**

```SCSS
/* SCSS SYNTAX */
$font-stack:    Helvetica, sans-serif;
$primary-color: #333;

body {
  font: 100% $font-stack;
  color: $primary-color;
}
```
```SASS
/* SASS SYNTAX */
$font-stack:    Helvetica, sans-serif
$primary-color: #333

body
  font: 100% $font-stack
  color: $primary-color
```
